Team-Inframe/Inframe-Backend

config/settings.py
config/urls.py
sticker/admin.py
sticker/apps.py
sticker/models.py
sticker/tests.py
sticker/urls.py
sticker/views.py

[test] 세팅 가이드

---

config/settings.py
config/urls.py
custom_frame/admin.py
custom_frame/apps.py
custom_frame/models.py
custom_frame/tests.py
custom_frame/urls.py
custom_frame/views.py

- resolved #(19)
모델, url, 만듬 
이상 무!

[feat] 커스텀 프레임 모델링 구현

---

custom_frame/serializer.py
custom_frame/urls.py
custom_frame/view2.py
custom_frame/views.py

- resolved #(31)
나의 커스텀 프레임 목록 조회 수정 
없음

[feat] 내가 저장한 커스텀 프레임 목록 조회

---

custom_frame/models.py
custom_frame/urls.py
custom_frame/view2.py
frame/urls.py

- resolved #42
내가 만든 커스텀 프레임 목록 조회
내가 만든 커스텀 프레임 목록 조회

[feat] 내가 만든 커스텀 프레임 목록 조회

---

config/urls.py
custom_frame/urls.py
frame/urls.py
photo/urls.py
sticker/views.py
user/urls.py

[deploy] 서버 배포

---

config/urls.py
docker-compose.yml

- resolved #(61)
도커 항시 빌드 기능 추가
리뷰어가 검토할 때 중점을 두어야 할 부분, 질문, 공유 사항을 작성해주세요

[Chore] 도커 항시 빌드 기능 추가

---

config/settings.py
config/urls.py
custom_frame/urls.py
custom_frame/views1.py
docker-compose.yml
frame/urls.py
frame/views.py
photo/urls.py
user/urls.py

- resolved #62
s3 업로드 경로 수정
엔드포인트 수정

[feat] s3 업로드 경로 수정

---

.github/workflows/cd.yml
.github/workflows/ci.yml
Dockerfile
docker-compose.yml

- resolved #(65)
CI/CD 파이프라인 구축
없음

[chore] CI/CD 파이프라인 구축

---

.github/workflows/cd.yml
docker-compose-prod.yml

- resolved #68 
cd 파이프라인 수정
cd 파이프라인 수정

[chore] cd 파이프라인 수정

---

.github/workflows/cd.yml
docker-compose-prod.yml

[test] cd 테스트

---

.github/workflows/cd.yml

[test] script 수정

---

.github/workflows/cd.yml

이번 작업에서 구현하거나 수정한 내용을 구체적으로 작성해주세요
리뷰어가 검토할 때 중점을 두어야 할 부분, 질문, 공유 사항을 작성해주세요

[fix] cd 오류 해결

---

docker-compose-prod.yml
frame/models.py
frame/views.py

- resolved #77 
특정 이미지 모델 조건 추가

[fix] 특정 이미지 모델 조건 추가

---

docker-compose-prod.yml

[fix] 네트워크 설정 추가

---

docker-compose-prod.yml

- resolved #(issue_num)
이번 작업에서 구현하거나 수정한 내용을 구체적으로 작성해주세요
리뷰어가 검토할 때 중점을 두어야 할 부분, 질문, 공유 사항을 작성해주세요

hotfix: 경로 수정

---

docker-compose-prod.yml

[test] 주석 처리

---

custom_frame/view2.py
docker-compose-prod.yml

- resolved #83 
bookmarks 응답값 추가

[feat] bookmarks 응답값 추가

---

config/urls.py
custom_frame/view2.py

- resolved #(85)
북마크 삭제 기능 구현
없음

[feat] 북마크 삭제 기능 구현

---

sticker/urls.py
sticker/views.py

- resolved #87 
스티커 목록 조회 api 구현

[feat] 스티커 목록 조회 api 구현

---

custom_frame/view2.py

[feat] 북마크 여부 응답값 추가

---

config/settings.py
config/urls.py
docker-compose-prod.yml
docker-compose.yml

- resolved #98
- 
배포 환경에서 redis 적용
배포 환경에서 redis 적용

[chore] 배포 환경에서 redis 적용

---

config/settings.py
config/utils.py

- resolved #107 
cloudfront 연결
env 업데이트 있습니다

[feat] cloudfront 연결

---

config/settings.py
docker-compose-prod.yml

- resolved #106
배포환경에서 rabbitmq, celery 연동
배포환경에서 rabbitmq, celery 연동

[chore] 배포환경에서 rabbitmq, celery 연동

---

config/settings.py
config/utils.py
docker-compose-prod.yml

- resolved #(issue_num)
이번 작업에서 구현하거나 수정한 내용을 구체적으로 작성해주세요
리뷰어가 검토할 때 중점을 두어야 할 부분, 질문, 공유 사항을 작성해주세요

[deploy] 메인브랜치로 병합

---

config/urls.py
docker-compose-prod.yml
photo/urls.py
photo/views.py

- resolved #117
사진 단일 조회 기능 추가
없음

[feat] 사진 단일 조회 기능 추가

---

config/urls.py
docker-compose-prod.yml
frame/views.py
photo/views.py

- resolved #120 issue_num
최종사진 단일 조회
없음

[feat] 최종사진 단일 조회

---

config/urls.py
frame/views.py

- resolved #123 issue_num
- 
배경 프롬프트 수정
없음

[feat] 배경 프롬프트 수정

---

config/urls.py
custom_frame/views.py
photo/views.py

- resolved #126 issue_num
모든 목록 조회 최신순 기능 추가
없음

[feat] 모든 목록 조회 최신순 기능 추가

---

custom_frame/views.py

- resolved #128 issue_num
커스텀프레임 생성 기능에서 북마크, 삭제 여부 제거
없음

[feat] 커스텀프레임 생성 기능에서 북마크, 삭제 여부 제거

---

config/urls.py
custom_frame/urls.py
custom_frame/views.py

- resolved #138
날씨 프레임 조회 기능 구현
날씨 프레임 조회 기능 구현

[feat] 날씨 프레임 조회 기능 구현

---

sticker/views.py

- resolved #141 issue_num
스티커 최신순 정렬
없음

[feat] 스티커 최신순 정렬

---

config/urls.py
docker-compose-prod.yml
sticker/views.py

- resolved #143 issue_num
스티커 프롬프트 수정
없음

[feat] 스티커 프롬프트 수정

---

sticker/views.py

- resolved #(145)
스티커 생성 API 응답 수정
스티커 생성 API 응답 수정

[feat] 스티커 생성 API 응답 수정

---

docker-compose-prod.yml
sticker/views.py

[deploy] 메인 브랜치로 합병

---

docker-compose-prod.yml

- resolved #(148)
도커이미지수정
도커이미지수정

[feat] 도커이미지수정
